"use strict";

let divContainer = document.createElement("div");
divContainer.setAttribute("class", "container");
document.body.appendChild(divContainer);
let scrip = document.getElementsByTagName("script")[0];
document.body.insertBefore(divContainer, scrip);
console.log(divContainer);
let h1 = document.createElement("h1");
divContainer.appendChild(h1);
h1.innerText = "WHAT PEOPLE SAY";
h1.style.color = "#BD9259";
h1.style.fontSize = "17px";
h1.style.fontWeight = "bold";
h1.style.textAlign = "center";
h1.style.marginTop = "30px";
let h2 = document.createElement("h2");
divContainer.appendChild(h2);
h2.innerText = "Reviews";
h2.style.color = "#B1B1B1";
h2.style.fontSize = "70px";
h2.style.fontWeight = "bold";
h2.style.textAlign = "center";
let divRow = document.createElement("div");
divRow.setAttribute("class","row");
divContainer.appendChild(divRow);
divRow.style.marginTop = "50px";
let divCol4a = document.createElement("div");
divCol4a.setAttribute("class","col-4");
divRow.appendChild(divCol4a);
let paragraph1 = document.createElement("p");
paragraph1.innerText = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa nisi consectetur iusto, unde sed in perferendis sint! Doloremque, in facere?";
divCol4a.appendChild(paragraph1);
paragraph1.style.textAlign = "center";
paragraph1.style.padding = "0 50px";
paragraph1.style.lineHeight = "30px";
paragraph1.style.color = "#A3A3A3";
paragraph1.style.fontSize = "17px";
let imgs1 = document.createElement("div");
divCol4a.appendChild(imgs1);
imgs1.style.display = "flex";
imgs1.style.justifyContent = "center";
imgs1.style.textAlign = "center";
let img1 = document.createElement("img");
img1.setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHTgHIkeUje7FBlWs_Uh8ucpyoBkP7ERqu2_z4pT7LAqUz6Mue");
imgs1.appendChild(img1);
img1.style.borderRadius = "100%";
img1.style.width = "100px";
img1.style.height = "100px";
let h5element1 = document.createElement("h5");
divCol4a.appendChild(h5element1);
h5element1.innerText = "Los Angeles";
h5element1.style.textAlign = "center";
h5element1.style.color = "#C39C68";
h5element1.style.marginTop = "20px";
let divCol4b = document.createElement("div");
divCol4b.setAttribute("class","col-4");
divRow.appendChild(divCol4b);
let paragraph2 = document.createElement("p");
divCol4b.appendChild(paragraph2);
paragraph2.innerText = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa nisi consectetur iusto, unde sed in perferendis sint! Doloremque, in facere?";
paragraph2.style.textAlign = "center";
paragraph2.style.color = "#A3A3A3";
paragraph2.style.padding = "0 50px";
paragraph2.style.fontSize = "17px";
paragraph2.style.lineHeight = "30px";
let imgs2 = document.createElement("div");
divCol4b.appendChild(imgs2);
imgs2.style.display = "flex";
imgs2.style.justifyContent = "center";
imgs2.style.alignItems = "center";
let img2 = document.createElement("img");
img2.setAttribute("src","https://thenypost.files.wordpress.com/2019/03/190309-nyc-bankrupt.jpg?quality=90&strip=all&w=618&h=410&crop=1");
imgs2.appendChild(img2);
img2.style.borderRadius = "100%";
img2.style.width = "100px";
img2.style.height = "100px";
let h5element2 = document.createElement("h5");
divCol4b.appendChild(h5element2);
h5element2.innerText = "New York";
h5element2.style.color = "#C39C68";
h5element2.style.textAlign = "center";
h5element2.style.marginTop = "20px";
let divCol4c = document.createElement("div");
divCol4c.setAttribute("class","col-4");
divRow.appendChild(divCol4c);
let paragraph3 = document.createElement("p");
paragraph3.innerText = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa nisi consectetur iusto, unde sed in perferendis sint! Doloremque, in facere?";
divCol4c.appendChild(paragraph3);
paragraph3.style.textAlign = "center";
paragraph3.style.color = "#A3A3A3";
paragraph3.style.fontSize = "17px";
paragraph3.style.lineHeight = "30px";
paragraph3.style.padding = "0 50px";
let imgs3 = document.createElement("div");
divCol4c.appendChild(imgs3);
imgs3.style.display = "flex";
imgs3.style.justifyContent = "center";
imgs3.style.alignItems = "center";
let img3 = document.createElement("img");
img3.setAttribute("src","https://cdn.civitatis.com/estados-unidos/nueva-york/galeria/capitolio-washington.jpg");
imgs3.appendChild(img3);
img3.style.borderRadius = "100%";
img3.style.width = "100px";
img3.style.height = "100px";
let h5element3 = document.createElement("h5");
h5element3.innerText = "Washington";
divCol4c.appendChild(h5element3);
h5element3.style.color = "#C39C68";
h5element3.style.textAlign = "center";
h5element3.style.marginTop = "20px";